### ISSUE TITLE
Every time edit the editor, it will be refreshed.

### ISSUE THREAD

**Issue by slowrookie** [materiahq/ngx-monaco-editor#1]
Hi @GeoAstronaute ,
I use the package with electron + angular 6, but every time edit the editor, it will be refreshed.
I found the reason is in [monaco-editor.component.ts](https://github.com/GeoAstronaute/ngx-monaco-editor/blob/master/src/ngx-monaco-editor/src/lib/components/monaco-editor/monaco-editor.component.ts), 
the line at 79 ( this.editor.setValue(changes.code.currentValue);), should be removed.  should not be reassgined.

**Comment by jmarc-roy** [comment]
Hi @slowrookie,
Thanks for your feedback. I will look at this and publish a new version soon.

We do not use double binding in our project, so we did not notice this bug. 
For a quick workaround you can use the editor as follow:

`<ngx-monaco-editor [options]="editorOptions" [code]="code" (codeChange)="latestCodeVal = $event"></ngx-monaco-editor>`

You will be able to store the latest code change in another variable (latestCodeVal in my example).

**Comment by jmarc-roy** [comment]
Fixed in v1.1.3
