### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by robertlevy** [materiahq/ngx-monaco-editor#10]
Buried in /docs/3rdpartylicenses.txt I see that this is meant to be MIT licensed.  It would be helpful to have this more clearly stated in a LICENSE file in the root and in the package.json.

**Comment by thyb** [comment]
Thanks for the feedback, it has been done in https://github.com/materiahq/ngx-monaco-editor/commit/4f91644284104f5c5616038f595bbe1e0d3088a5 and https://github.com/materiahq/ngx-monaco-editor/commit/f02947476c320b31a7fa6d001715042db6c61214.
