### ISSUE TITLE
'can only have one anonymous define call per script file' in console 

### ISSUE THREAD

**Issue by amily666** [materiahq/ngx-monaco-editor#11]
i'm use ngx-monaca-deditor in angular7, and get the error 'can only have one anonymous define call per script file' in console, what can i do ?

**Comment by amily666** [comment]
i'm use ngx-monaca-deditor in angular7, and get the error 'can only have one anonymous define call per script file' in console, what can i do ?

**Comment by jmarc-roy** [comment]
Hi @amily666,

Do you have more informations to share ? Are you using our library in electron or in the browser ?

I found issues with the same error message on the monaco-editor github repo: [#1249](https://github.com/microsoft/monaco-editor/issues/1249) and [#19](https://github.com/microsoft/vscode-loader/issues/19).
Maybe you have the same issue, do you use jquery in your angular app ?

**Comment by stagefright5** [comment]
@GeoAstronaute I am able to reproduce this in combination with a dynamic require of another module (`strong-soap`). My env is Electron v9.
Here is the repo for reproducing: [repo](https://github.com/stagefright5/strong-soap-dynamic-module-load-issue)
The steps to reproduce is the the root [README.md](https://github.com/stagefright5/strong-soap-dynamic-module-load-issue#strong-soap-dynamic-module-load-issue)

I have raised the issue in both `monaco-editor` and `strong-soap` repos:
- https://github.com/microsoft/monaco-editor/issues/2283
- https://github.com/strongloop/strong-soap/issues/304
