### ISSUE TITLE
Help please: how can we show the syntax error, highlight error in editor?

### ISSUE THREAD

**Issue by datavisorfrankhe** [materiahq/ngx-monaco-editor#12]
Hello,
We have a requirement to have auto checking for syntax error, may I ask if this is supported by this angular library?

For example, I am using it to provide sql support, and if I typed in

wrong_select * form field

I want the wrong_select to be indicated as wrong. and if I mouse hovering, suggestion for fix will appear.

Can I have any example on how to enable the syntax error checking?

I checked monaco github, they support it like this:

https://github.com/microsoft/monaco-editor/issues/1477
Using setModelMarkers

But I do not know how to use that solution in this angular plugin.

Can anyone help here?

Thanks in advance.

**Comment by doczoidberg** [comment]
@datavisorfrankhe did you found a solution?

**Comment by batnyu** [comment]
Hello,
You can find his issue with a solution posted on the monaco editor repo in the following link 
[https://github.com/microsoft/monaco-editor/issues/1527#issuecomment-517201647](url)
