### ISSUE TITLE
ngx-monaco-editor (ver8) should include monaco-editor ver0.18.1 instead of ver0.17.1

### ISSUE THREAD

**Issue by beeyingl** [materiahq/ngx-monaco-editor#14]

**Comment by zerocewl** [comment]
Any news here?

The current dependency is monaco-editor@^0.15.6.

Is there an issue why the dependency can't be updated to 0.18.1?

**Comment by jmarc-roy** [comment]
Hi @beeyingl,

I published a new version of the library. monaco-editor is now no longer provided in the package, you have to install it manually.

It allows you to pick the version you want.
