### ISSUE TITLE
Angular: 8.2.14 - error TS1086: An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by GregorBiswanger** [materiahq/ngx-monaco-editor#19]
Hi,

first of all - Thank you for your work!

I created a new Angular 8 project with the current newest version and installed your package.
I can´t start the Angular App with `ng serve`. I got the following expection:

---------------- 8< -------------------------
ng serve
10% building 3/3 modules 0 activei ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.html

chunk {main} main.js, main.js.map (main) 2.05 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 122 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 9.74 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 340 kB [initial] [rendered]
Date: 2019-12-21T12:18:05.135Z - Hash: 9a1992aed70d1fd9e5f3 - Time: 11071ms

ERROR in node_modules/monaco-editor/esm/vs/editor/editor.api.d.ts:50:9 - error TS1086: An accessor cannot be declared in an ambient context.

50     get token(): CancellationToken;
           ~~~~~
node_modules/monaco-editor/esm/vs/editor/editor.api.d.ts:125:9 - error TS1086: An accessor cannot be declared in an ambient context.

125     get fsPath(): string;
            ~~~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.

---------------- >8 -------------------------

Do you have an idea for the solution?

**Comment by jmarc-roy** [comment]
Hi @GregorBiswanger,

You have to downgrade monaco-editor to v0.18.1, because the newer 0.19.0 version requires typescript v3.7.0. Since angular v8 needs typescript version < 3.6.0, you won't be able to use monaco-editor v0.19.0 with angular v8. You have to wait until angular v9.

**Comment by GregorBiswanger** [comment]
Thank you for the extreme fast answer and support!
Works fine now... Thank you...

**Comment by jmarc-roy** [comment]
No problem. Thanks for opening an issue.
Very useful, I will update the README to warn other users.

**Comment by vocaris** [comment]
I can only agree with @GregorBiswanger: Thank you for your work. It's great!

But I didn't get it to work. I downgraded to version 0.19.0 but got a similar error:


`ng serve
Your global Angular CLI version (10.1.3) is greater than your local
version (8.3.29). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
i ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.html

chunk {main} main.js, main.js.map (main) 2.08 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 154 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.css, styles.css.map (styles) 414 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 346 kB [initial] [rendered]
Date: 2021-05-11T18:00:55.312Z - Hash: bc26a5325e98b1e5532d - Time: 8517ms

ERROR in ../node_modules/@materia-ui/ngx-monaco-editor/lib/components/monaco-editor/monaco-editor.component.d.ts:18:9 - error TS1086: An accessor cannot be declared in an ambient context.

18     get model(): monaco.editor.ITextModel;
           ~~~~~
../node_modules/@materia-ui/ngx-monaco-editor/lib/components/monaco-editor/monaco-editor.component.d.ts:19:9 - error TS1086: An accessor cannot be declared in an ambient context.

19     get modelMarkers(): monaco.editor.IMarker[];
           ~~~~~~~~~~~~
../node_modules/@materia-ui/ngx-monaco-editor/lib/interfaces/monaco.d.ts:56:13 - error TS1086: An accessor cannot be declared in an ambient context.

56         get token(): CancellationToken;
               ~~~~~
../node_modules/@materia-ui/ngx-monaco-editor/lib/interfaces/monaco.d.ts:140:13 - error TS1086: An accessor cannot be declared in an ambient context.

140         get fsPath(): string;
                ~~~~~~
../node_modules/@materia-ui/ngx-monaco-editor/lib/services/monaco-editor-loader.service.d.ts:9:9 - error TS1086: An accessor cannot be declared in an ambient context.

9     set monacoPath(value: string);
          ~~~~~~~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.`

Can you help me get it to work?
