### ISSUE TITLE
Access to other available editor options

### ISSUE THREAD

**Issue by ivanbatic** [materiahq/ngx-monaco-editor#2]
Thanks for the awesome work done with this module!
I'm interested in knowing if there's a particular reason for not passing an options object directly to Monaco, and instead exposing only a few parameters? 
```
    language: string;
    lineNumbers?: boolean;
    theme?: string;
    readOnly?: boolean;
    scrollBeyondLastLine?: boolean;
    automaticLayout?: boolean;
    minimap?: any;
```

I guess that you probably didn't need it for your own project, but would it be possible to just pass all options through to Monaco and maybe expose the editor instance, so I can manually configure it myself (register a custom theme, language service etc.)?

Thanks,
Ivan

**Comment by jmarc-roy** [comment]
Hi @ivanbatic,
thanks for your feedback. Yes it is correct we didn't needed more parameters for the moment.
But I agree, that it will be great to have all available Monaco options.
For the moment you can access the editor instance with a `@ViewChild(MonacoEditorComponent) monacoComponent: MonacoEditorComponent` => `this.monacoComponent.editor`.

**Comment by jmarc-roy** [comment]
Since v2.x all monaco-editor options are now supported.
