### ISSUE TITLE
Does it support json schemas?

### ISSUE THREAD

**Issue by faramos** [materiahq/ngx-monaco-editor#22]

**Comment by jmarc-roy** [comment]
Hi @faramos,

Yes [monaco-editor](https://microsoft.github.io/monaco-editor/index.html) support json schemas.

You can find the official example here: https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults.

With our library set the language to json:
`MonacoEditorComponent.options = {language: 'json'}`.
