### ISSUE TITLE
Is there a way to change editor syntax language dynamically?

### ISSUE THREAD

**Issue by Pryanishnik** [materiahq/ngx-monaco-editor#23]
Is there a way to change editor syntax language dynamically? 
I tried approach as is used for themes, but it doesn't work

**Comment by jmarc-roy** [comment]
Hi @Pryanishnik,

As you suspect, It is the same approach as for Theme changing. The library components uses OnPush change detection strategy, so you have to provide a new reference of the options object to change the language. 

Here is a working example on [Stackblitz](https://stackblitz.com/edit/materia-ngx-monaco-editor-example-r7xdce).

**Comment by Pryanishnik** [comment]
Oh, thank you @GeoAstronaute . I missed assignment part I suppose, big thanks for Stackblitz:)
