### ISSUE TITLE
monaco-editor update to 0.21.2

### ISSUE THREAD

**Issue by samdoeswork** [materiahq/ngx-monaco-editor#37]
Hi! It would be nice to access monaco-editor 0.21.2. This is 7 months of updates, including top-level await.

Thanks in advance!

**Comment by hanneswidrig** [comment]
You can just point to the remote `unpkg.com` tied to 0.21.2.

**Comment by MirageDT** [comment]
> You can just point to the remote `unpkg.com` tied to 0.21.2.

This does not work and renders a blank screen for the editor. I have to stay on 0.18.1 otherwise I have no editor. 

(I am on Electron and can't do any other way than with a CDN)

**Comment by jmarc-roy** [comment]
Upgraded in v5.0.0
