### ISSUE TITLE
How to addAction ? addCommand ?

### ISSUE THREAD

**Issue by noririco** [materiahq/ngx-monaco-editor#39]
https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandalonecodeeditor.html

How can I use this feature ? 

Thanks!

**Comment by jmarc-roy** [comment]
Hi @noririco,

to use all features from the editor you should retrieve the editor instance as specified in the README [here](https://github.com/materiahq/ngx-monaco-editor#access-editor-instance)
