### ISSUE TITLE
Can't get materiaLoadMonacoEditor to work (trying to load Monaco from CDN)

### ISSUE THREAD

**Issue by iJungleboy** [materiahq/ngx-monaco-editor#4]
I've tried this for over an hour and I just can't get it to work. 

What I'm trying to do is get monaco from a CDN, so I don't have to distribute it with my application. So I need to set the root path, and from reading your code, I get the impression that I must simply add an attribute and put the value in that. I tried various versions of:

```
<ngx-monaco-editor [options]="editorOptions" [(ngModel)]="code"
materiaLoadMonacoEditor='https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.16.2/min/vs'></ngx-monaco-editor>

```

as well as versions of 

```
  constructor(monacoConfig: MonacoEditorLoaderService) {
    monacoConfig.monacoPath = 'https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.16.2/min/vs';
   }
```

Neither work - i get errors or it doesn't do what I expect. Can you help?

**Comment by jmarc-roy** [comment]
Hi @iJungleboy,

You are right the directive doesn't seems to work as expected. And changing the monacoPath in the MonacoEditorLoaderService either. I would recommand to install monaco-editor package locally, as describe in the readme for now.

I will take a look at this very soon.
Thanks for your feedback!

**Comment by jmarc-roy** [comment]
Since v3.0.x, you can now load monaco-editor lib from a CDN.
