### ISSUE TITLE
Warning materia-ui-ngx-monaco-editor.js depends on 'css-element-queries'. CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by stagefright5** [materiahq/ngx-monaco-editor#52]
![image](https://user-images.githubusercontent.com/15051871/111040091-8e56b380-8457-11eb-90ab-c5be0e5e5bbf.png)

Is this something to be concerned about?

**Comment by jmarc-roy** [comment]
Hi @stagefright5 ,
You should not have this error anymore with v5.0.0, I removed this dependency (cf: https://github.com/materiahq/ngx-monaco-editor/blob/master/src/ngx-monaco-editor/package.json).
If you are using an older version, you can remove this warning by settings `allowedCommonJsDependencies` in your angular config file:
```
"architect": {
  "build": {
    "builder": "@angular-devkit/build-angular:browser",
    "options": {
      "allowedCommonJsDependencies": ["css-element-queries"]
    }
  }
}
```

**Comment by stagefright5** [comment]
> Hi @stagefright5 ,
> You should not have this error anymore with v5.0.0, I removed this dependency (cf: https://github.com/materiahq/ngx-monaco-editor/blob/master/src/ngx-monaco-editor/package.json).
> If you are using an older version, you can remove this warning by settings `allowedCommonJsDependencies` in your angular config file:
> ```
> "architect": {
>   "build": {
>     "builder": "@angular-devkit/build-angular:browser",
>     "options": {
>       "allowedCommonJsDependencies": ["css-element-queries"]
>     }
>   }
> }
> ```

Thanks for the reply. I am waiting for the Monaco load issue #48 to get fixed to upgrade to v5.
