### ISSUE TITLE
[Q] Is this package no longer maintained?

### ISSUE THREAD

**Issue by stagefright5** [materiahq/ngx-monaco-editor#59]
It seems like this package is no longer maintained actively. Please confirm if this is the case, so that we the users can move on.

Thanks

**Comment by jmarc-roy** [comment]
Hi @stagefright5,

The package is still maitained, but with a lower activity. 
I will still continue to update it when major bump of angular version and monaco are released.

**Comment by stagefright5** [comment]
> Hi @stagefright5,
> 
> The package is still maitained, but with a lower activity. 
> I will still continue to update it when major bump of angular version and monaco are released.

As you might already know, ar angular 12 was released 3 days ago. This dependency library still is at angular 10.
That's why asked.
Anyway, good to know it's still maintained.

Thanks

**Comment by jmarc-roy** [comment]
Yes it's on purpose that the library is build with angular v9. It's to maintain compatibility for angular v9 to v12. 
It's not an issue at all for working with angular v12.
I will soon release a new library build with angular v12 and ivy, it will drop all previous version support.
