### ISSUE TITLE
MONACO_PATH is not set correctly

### ISSUE THREAD

**Issue by t3bld** [materiahq/ngx-monaco-editor#60]
I have problems loading the dependencies via CDN. I have tried to get the editor to run like in the example, but it looks like the MONACO_PATH is not set correctly:

```
providers: [{
  provide: MONACO_PATH,
  useValue: 'https://unpkg.com/monaco-editor@0.18.1/min/vs'
}],
```

> materia-ui-ngx-monaco-editor.js:67 GET http://localhost:3000/assets/monaco-editor/min/vs/loader.js net::ERR_ABORTED 404 (Not Found)

**Comment by jmarc-roy** [comment]
Hello @ArkasDev ,

Can you try with latest version v5.1.0 ?
Does this happen in electron or in the browser or both ?
