### ISSUE TITLE
Setup question

### ISSUE THREAD

**Issue by Rossco8** [materiahq/ngx-monaco-editor#61]
The demo on Stackblitz does not have 
```
"assets": [
                        { "glob": "**/*", "input": "node_modules/monaco-editor", "output": "assets/monaco-editor/" }
                    ],
```
Is it necessary?
And should it be 
```
{ "glob": "**/*", "input": "node_modules/@materia-ui/ngx-monaco-editor", "output": "assets/monaco-editor/" }
```

**Comment by jmarc-roy** [comment]
Hi @Rossco8 ,

You have 2 way to load `monaco-editor` package with our library:
- From a remote resource, like a CDN url: in this case no need to install `monaco-editor` package and no need to modify angular.json like you ask (on Stackblitz this is the case)
- From local installation: in this case you have to install `monaco-editor` package, and modify your angular.json config to copy the lib in your application assets

**Comment by Rossco8** [comment]
ok, thanks, that makes sense
