### ISSUE TITLE
Are there anyway to create custom theme editor?

### ISSUE THREAD

**Issue by ghost** [materiahq/ngx-monaco-editor#7]
Are there anyway to create custom theme editor?
Thanks

**Comment by jmarc-roy** [comment]
Hi @Devkoja10 ,

You can set a custom theme editor like in this monaco-editor [official example](https://microsoft.github.io/monaco-editor/playground.html#customizing-the-appearence-tokens-and-colors).

So basically when using our library you should wait that monaco is loaded, and then define your custom theme. You can use our MonacoEditorLoaderService to know when monaco is loaded:
```
constructor(private monacoLoaderService: MonacoEditorLoaderService) {
      this.monacoLoaderService.isMonacoLoaded.pipe(
        filter(isLoaded => isLoaded),
        take(1),
      ).subscribe(() => {
           // here we retrieve monaco instance
           this.monaco = ((window as any).monaco);

           // Do stuff with monaco instance
      });
}
```

You will then be able to define a custom theme like shown in the official monaco-editor example.

Hope it answer your question !

**Comment by maks-humeniuk** [comment]
Hello. I tried this approach, but unfortunately it doesn't work. It seems that theme is either not applied or it doesn't affect the editor instance I use on the page. Could you please help me to figure out what's wrong? I'm using your library, not the [original](https://github.com/atularen/ngx-monaco-editor), because it doesn't have problem with resizing. Though the original one didn't have problems with theming. They use `(onInit)` event output on `<ngx-monaco-editor>`. Maybe its better than using service, because in their case the event is more attached to specific editor instance.

**Comment by maks-humeniuk** [comment]
For anyone who's interested in resolving the issue, I ended up using [ngx-monaco-editor](https://github.com/atularen/ngx-monaco-editor) with [automaticLayout: true](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditoroptions.html#automaticlayout) setting. Themes work fine there.

**Comment by jmarc-roy** [comment]
@Halfist,
I made a quick example, based on the official example, and it works as expected:

```typescript
import { Component } from '@angular/core';
import { MonacoEditorLoaderService } from '@materia-ui/ngx-monaco-editor';
import { filter, take } from 'rxjs/operators';

@Component({
  selector: 'app-root',
  template: `<ngx-monaco-editor [options]="editorOptions" [(ngModel)]="code"></ngx-monaco-editor>`,
  styles: [`ngx-monaco-editor {
    height: 500px;
    width: 500px;
  }`]
})
export class AppComponent {
  editorOptions = {theme: 'myCustomTheme', language: 'text/html'};
  code: string = this.getCode();

  constructor(private monacoLoaderService: MonacoEditorLoaderService) {
    this.monacoLoaderService.isMonacoLoaded.pipe(
      filter(isLoaded => isLoaded),
      take(1)
    ).subscribe(() => {
      (window as any).monaco.editor.defineTheme('myCustomTheme', {
        base: 'vs', // can also be vs-dark or hc-black
        inherit: true, // can also be false to completely replace the builtin rules
        rules: [
          { token: 'comment', foreground: 'ffa500', fontStyle: 'italic underline' },
          { token: 'comment.js', foreground: '008800', fontStyle: 'bold' },
          { token: 'comment.css', foreground: '0000ff' } // will inherit fontStyle from `comment` above
        ]
      });
    });
  }

  getCode() {
    // tslint:disable-next-line: max-line-length
    return '<html><!-- // !!! Tokens can be inspected using F1 > Developer: Inspect Tokens !!! -->\n<head>\n	<!-- HTML comment -->\n	<style type="text/css">\n		/* CSS comment */\n	</style>\n	<script type="javascript">\n		// JavaScript comment\n	</'+"script>\n</head>\n<body></body>\n</html>";
  }
}
```

Maybe your issue is that you were not configuring monaco before the monaco component are displayed.
